/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.service.builder.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.training.service.builder.model.TrackerEntry;
import com.liferay.training.service.builder.service.TrackerEntryLocalServiceUtil;

/**
 * The extended model base implementation for the TrackerEntry service. Represents a row in the &quot;tracking_TrackerEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrackerEntryImpl}.
 * </p>
 *
 * @author Shanon Mathai
 * @see TrackerEntryImpl
 * @see com.liferay.training.service.builder.model.TrackerEntry
 * @generated
 */
public abstract class TrackerEntryBaseImpl extends TrackerEntryModelImpl
	implements TrackerEntry {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tracker entry model instance should use the {@link TrackerEntry} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			TrackerEntryLocalServiceUtil.addTrackerEntry(this);
		}
		else {
			TrackerEntryLocalServiceUtil.updateTrackerEntry(this);
		}
	}
}